const products = [
{
  id: 1,
  name: "Vợt Cầu Lông Carbon Training Màu Xanh",
  price: "630.000 ₫",
  brand: "VNB",
  material: "Carbon",
  length: "675mm",
  weight: "150g",
  imageUrl: "img/votcaulong/vot-cau-long-vnb-carbon-training-150g-5.png",
  description: "Vợt cầu lông dành cho người mới tập luyện với trọng lượng lớn để tăng sức mạnh tay."
},
{
  id: 2,
  name: "Vợt Cầu Lông V200 Hàng VN",
  price: "520.000 ₫",
  brand: "V200",
  material: "Carbon Fiber",
  length: "675mm",
  weight: "85g",
  imageUrl: "img/votcaulong/vot-cau-long-v200-do-2.png",
  description: "Vợt cầu lông V200 thiết kế gọn nhẹ, phù hợp cho người chơi phong trào."
},
{
  id: 3,
  name: "Vợt Cầu Lông VNB V88 Carbon Training Màu Cam",
  price: "630.000 ₫",
  brand: "VNB",
  material: "Carbon",
  length: "675mm",
  weight: "150g",
  imageUrl: "img/votcaulong/vot-cau-long-vnb-v88-3.png",
  description: "Phiên bản cam nổi bật của dòng VNB V88 dành cho người chơi nâng cao thể lực."
},
{
  id: 4,
  name: "Vợt Cầu Lông RedSon Shape ESG",
  price: "4.500.000 ₫",
  brand: "RedSon",
  material: "Carbon + Graphite",
  length: "675mm",
  weight: "85g",
  imageUrl: "img/votcaulong/vot-cau-long-redson-shape-esg.png",
  description: "Vợt cầu lông cao cấp RedSon, nổi bật với độ bền và độ chính xác cao."
},
{
  id: 5,
  name: "Vợt Cầu Lông The 3rd Game ARC FB",
  price: "1.500.000 ₫",
  brand: "The 3rd",
  material: "Graphite",
  length: "675mm",
  weight: "83g",
  imageUrl: "img/votcaulong/vot-cau-long-the-3rd-game-arc-fb-do.png",
  description: "Vợt dành cho vận động viên tấn công với khung vợt linh hoạt và cân bằng tốt."
},
{
  id: 6,
  name: "Vợt Cầu Lông TC88C",
  price: "799.000 ₫",
  brand: "VNB",
  material: "Carbon",
  length: "675mm",
  weight: "88g",
  imageUrl: "img/votcaulong/vot-cau-long-vnb-tc88c-1.png",
  description: "Thiết kế chắc chắn, vợt TC88C phù hợp với người chơi trung cấp."
},
{
  id: 7,
  name: "Vợt Cầu Lông V88 Xanh",
  price: "529.000 ₫",
  brand: "VNB",
  material: "Carbon",
  length: "675mm",
  weight: "88g",
  imageUrl: "img/votcaulong/vot-cau-long-vnb-v88-xanh-chinh-hang-1.png",
  description: "Vợt VNB V88 phiên bản xanh chính hãng, trọng lượng vừa phải, dễ điều khiển."
},
{
  id: 8,
  name: "Vợt Cầu Lông Yonex Astrox 99 LCW",
  price: "3.689.000 ₫",
  brand: "Yonex",
  material: "Graphite + Tungsten",
  length: "675mm",
  weight: "3U (~85-89g)",
  imageUrl: "img/votcaulong/vot-cau-long-yonex-astrox-99-lcw-2.png",
  description: "Yonex Astrox 99 LCW là mẫu vợt cao cấp với độ chính xác và khả năng tấn công mạnh mẽ."
  },
  {
  id: 9,
  name: "Giày cầu lông Victor A396 A",
  price: "1.290.000 ₫",
  brand: "Victor",
  material: "Da tổng hợp",
  length: "27 cm",
  weight: "300g",
  description: "Thiết kế chắc chắn, bám sàn tốt, phù hợp chơi cầu lông trong nhà.",
  imageUrl: "img/giay/giay-cau-long-victor-a396-a-trang-chinh-hang_1745873894.png"
},
{
  id: 10,
  name: "Giày cầu lông Victor P8500Nlite AT",
  price: "2.390.000 ₫",
  brand: "Victor",
  material: "Lưới thoáng khí và da PU",
  length: "27.5 cm",
  weight: "290g",
  description: "Dòng giày cao cấp hỗ trợ bảo vệ cổ chân, đế cao su chống trượt.",
  imageUrl: "img/giay/giay-cau-long-victor-p8500nlite-at-trang-tim-chinh-hang_1745873404.png"
},
{
  id: 11,
  name: "Giày cầu lông Taro TR024-1",
  price: "499.000 ₫",
  brand: "Taro",
  material: "Vải tổng hợp và da PU",
  length: "27 cm",
  weight: "310g",
  description: "Giày cầu lông giá rẻ phù hợp cho người mới chơi, đế êm và thoải mái.",
  imageUrl: "img/giay/giay-cau-long-taro-tr024-1-xanh-ngoc_1732235089.png"
},
{
  id: 12,
  name: "Giày cầu lông Taro TR024-2",
  price: "499.000 ₫",
  brand: "Taro",
  material: "Vải tổng hợp và da PU",
  length: "27 cm",
  weight: "310g",
  description: "Phiên bản nâng cấp của TR024-1, thiết kế khỏe khoắn và bền bỉ.",
  imageUrl: "img/giay/giay-cau-long-taro-tr024-2-trang-den_1732235436.png"
},
{
  id: 13,
  name: "Giày cầu lông Yonex Aerus Z Men Flash Green",
  price: "2.689.000 ₫",
  brand: "Yonex",
  material: "Power Cushion+, Double Russel Mesh",
  length: "28 cm",
  weight: "270g",
  description: "Mẫu giày nhẹ nhất của Yonex, hỗ trợ phản xạ nhanh, cực kỳ êm ái.",
  imageUrl: "img/giay/giay-cau-long-yonex-aerus-z-men-flash-green-chinh-hang_1746231911.png"
},
{
  id: 14,
  name: "Giày cầu lông Victor C90Nlite A",
  price: "2.390.000 ₫",
  brand: "Victor",
  material: "Da PU cao cấp và vải thoáng khí",
  length: "27.5 cm",
  weight: "295g",
  description: "Thiết kế hiện đại, độ bám tốt, hỗ trợ di chuyển linh hoạt.",
  imageUrl: "img/giay/giay-cau-long-victor-c90nlite-a-trang-chinh-hang_1745870700.png"
},
{
  id: 15,
  name: "Giày cầu lông Lining AYTU025-1 chính hãng",
  price: "1.325.000 ₫",
  brand: "Lining",
  material: "Synthetic leather + EVA",
  length: "27.5 cm",
  weight: "285g",
  description: "Mẫu giày tầm trung với thiết kế mạnh mẽ, phù hợp cả nam và nữ.",
  imageUrl: "img/giay/giay-cau-long-lining-aytu025-1-chinh-hang_1745634417.png"
},
{
  id: 16,
  name: "Giày cầu lông Yonex SHB 65X4 2025",
  price: "1.809.000 ₫",
  brand: "Yonex",
  material: "Power Cushion, Double Mesh",
  length: "28 cm",
  weight: "280g",
  description: "Mẫu giày thế hệ mới của Yonex với khả năng hấp thụ sốc cực tốt.",
  imageUrl: "img/giay/giay-cau-long-yonex-shb-65x4-trang-2025-chinh-hang_1736972553.png"
},
{
  id: 17,
  name: "Quần Cầu Lông Taro TR024-Q01 Nam - Đỏ Chính Hãng",
  price: "139.000 ₫",
  brand: "Taro",
  material: "Polyester co giãn",
  length: "M",
  weight: 190,
  description: "Quần cầu lông Taro TR024-Q01 màu đỏ, thiết kế năng động, chất liệu thoáng mát, thích hợp luyện tập thể thao.",
  imageUrl: "img/quan/quan-cau-long-taro-tr024-q01-nam-do-chinh-hang_1745803083.png"
},
{
  id: 18,
  name: "Quần cầu lông Yonex SM2570 Nam - Dark Gull Gray chính hãng",
  price: "369.000 ₫",
  brand: "Yonex",
  material: "Vải tổng hợp cao cấp",
  length: "L",
  weight: 210,
  description: "Quần cầu lông Yonex SM2570 màu Dark Gull Gray, form chuẩn thể thao, thoát nhiệt tốt, phù hợp thi đấu chuyên nghiệp.",
  imageUrl: "img/quan/quan-cau-long-yonex-sm2570-nam-dark-gull-gray-chinh-hang_1745877646.png"
},
{
  id: 19,
  name: "Quần cầu lông Yonex SM2570 Nam - Maritime Blue chính hãng",
  price: "369.000 ₫",
  brand: "Yonex",
  material: "Polyester thoáng khí",
  length: "L",
  weight: 210,
  description: "Quần cầu lông Yonex SM2570 màu Maritime Blue, chất liệu mịn, khô nhanh, thích hợp chơi thể thao thường xuyên.",
  imageUrl: "img/quan/quan-cau-long-yonex-sm2570-nam-maritime-blue-chinh-hang_1745883578.png"
},
{
  id: 20,
  name: "Quần cầu lông Yonex SM2765 - Anthracite chính hãng",
  price: "279.000 ₫",
  brand: "Yonex",
  material: "Vải sợi microfiber",
  length: "M",
  weight: 205,
  description: "Quần cầu lông Yonex SM2765 màu Anthracite, kiểu dáng hiện đại, bền bỉ, đàn hồi tốt, chống nhăn hiệu quả.",
  imageUrl: "img/quan/quan-cau-long-yonex-sm2765-anthracite-chinh-hang_1745875975.png"
},
{
  id: 21,
  name: "Quần cầu lông Yonex SM2765 - Apple Cinnamon chính hãng",
  price: "279.000 ₫",
  brand: "Yonex",
  material: "Polyester pha cotton",
  length: "S",
  weight: 200,
  description: "Quần cầu lông Yonex SM2765 màu Apple Cinnamon mang phong cách trẻ trung, thấm hút mồ hôi hiệu quả.",
  imageUrl: "img/quan/quan-cau-long-yonex-sm2765-apple-cinnamon-chinh-hang_1745875866.png"
},
{
  id: 22,
  name: "Quần cầu lông Yonex SM2765 - Beet Red chính hãng",
  price: "300.000 ₫",
  brand: "Yonex",
  material: "Vải thun co giãn",
  length: "XL",
  weight: 215,
  description: "Quần cầu lông Yonex SM2765 màu Beet Red, thiết kế thoải mái, phù hợp mọi hoạt động thể thao.",
  imageUrl: "img/quan/quan-cau-long-yonex-sm2765-beet-red-chinh-hang_1745876747.png"
},
{
  id: 23,
  name: "Quần cầu lông Yonex SM2765 - Navy Peony chính hãng",
  price: "400.000 ₫",
  brand: "Yonex",
  material: "Polyester co giãn bốn chiều",
  length: "L",
  weight: 220,
  description: "Quần cầu lông Yonex SM2765 màu Navy Peony, form thể thao mạnh mẽ, đàn hồi cao, độ bền vượt trội.",
  imageUrl: "img/quan/quan-cau-long-yonex-sm2765-navy-peony-chinh-hang_1745875463.png"
},
{
  id: 24,
  name: "Quần cầu lông Yonex TSM2911 - Blue Berry chính hãng",
  price: "149.000 ₫",
  brand: "Yonex",
  material: "Sợi tổng hợp thoáng khí",
  length: "M",
  weight: 195,
  description: "Quần cầu lông Yonex TSM2911 màu Blue Berry thiết kế năng động, phù hợp luyện tập và thi đấu cường độ cao.",
  imageUrl: "img/quan/quan-cau-long-yonex-tsm2911-blue-berry-chinh-hang_1742496276.png"
},
{
  id: 25,
  name: "Balo Cầu Lông Kumpoo KB-521",
  price: "895.000 ₫",
  brand: "Kumpoo",
  material: "Polyester",
  length: "45cm",
  weight: 600,
  description: "Balo Cầu Lông Kumpoo KB-521 thiết kế gọn nhẹ, ngăn đựng vợt tiện lợi, chống nước nhẹ, phù hợp cho người chơi cầu lông chuyên nghiệp và bán chuyên.",
  imageUrl: "img/balo/balo-cau-long-kumpoo-kb-521_1742586089.png"
},
{
  id: 26,
  name: "Balo Cầu Lông Kumpoo Trẻ Em KB-523",
  price: "755.000 ₫",
  brand: "Kumpoo",
  material: "Polyester",
  length: "40cm",
  weight: 500,
  description: "Balo Cầu Lông Kumpoo KB-523 dành cho trẻ em, thiết kế năng động, màu sắc nổi bật, chống thấm nhẹ, bền bỉ theo thời gian.",
  imageUrl: "img/balo/balo-cau-long-kumpoo-tre-em-kb-523_1742585815.png"
},
{
  id: 27,
  name: "Balo Cầu Lông Taro TR024-BA01",
  price: "369.000 ₫",
  brand: "Taro",
  material: "Vải tổng hợp",
  length: "44cm",
  weight: 550,
  description: "Balo Cầu Lông Taro TR024-BA01 với thiết kế hiện đại, nhiều ngăn tiện dụng, phù hợp cho sinh viên và người chơi phong trào.",
  imageUrl: "img/balo/balo-cau-long-taro-tr024-ba01_1737743524.png"
},
{
  id: 28,
  name: "Balo cầu lông Victor Doraemon BR5035DRM A",
  price: "1.279.000 ₫",
  brand: "Victor",
  material: "Polyester cao cấp",
  length: "47cm",
  weight: 700,
  description: "Balo Victor Doraemon BR5035DRM A phiên bản giới hạn với họa tiết Doraemon độc đáo, chất liệu bền đẹp và thoáng khí.",
  imageUrl: "img/balo/balo-cau-long-victor-doraemon-br5035drm-a-trang-noi-dia-trung_1741566781.png"
},
{
  id: 29,
  name: "Balo cầu lông Yonex BAG02512EX",
  price: "2.779.000 ₫",
  brand: "Yonex",
  material: "Da PU kết hợp Polyester",
  length: "50cm",
  weight: 850,
  description: "Balo Yonex BAG02512EX cao cấp, thiết kế sang trọng, bảo vệ vợt tối ưu, dành cho người chơi chuyên nghiệp.",
  imageUrl: "img/balo/balo-cau-long-yonex-bag02512ex_1745435333.png"
},
{
  id: 30,
  name: "Balo Cầu Lông Yonex BAG524B0712Z",
  price: "699.000 ₫",
  brand: "Yonex",
  material: "Polyester",
  length: "46cm",
  weight: 620,
  description: "Balo Yonex BAG524B0712Z kiểu dáng thể thao, trọng lượng nhẹ, phù hợp tập luyện và thi đấu.",
  imageUrl: "img/balo/balo-cau-long-yonex-bag524b0712z_1740360621.png"
},
{
  id: 31,
  name: "Balo Cầu Lông Yonex BAG524B0812Z",
  price: "700.000 ₫",
  brand: "Yonex",
  material: "Polyester",
  length: "46cm",
  weight: 630,
  description: "Phiên bản mới của dòng BAG524B, thiết kế khỏe khoắn, tiện dụng với ngăn chứa rộng rãi.",
  imageUrl: "img/balo/balo-cau-long-yonex-bag524b0812z_1740369410.png"
},
{
  id: 32,
  name: "Balo Cầu Lông Kumpoo KB-425 Xám",
  price: "849.000 ₫",
  brand: "Kumpoo",
  material: "Polyester cao cấp",
  length: "45cm",
  weight: 610,
  description: "Balo Kumpoo KB-425 màu xám, phong cách trung tính, nhiều ngăn đựng, đệm lưng thoải mái.",
  imageUrl: "img/balo/tui-cau-long-kumpoo-k368-trang-xanh-chinh-hang_1742247697.png"
},
{
  id: 33,
  name: "Áo Cầu Lông Lining T72 Nam Trắng",
  price: 130000,
  brand: "Lining",
  material: "Polyester",
  length: "L",
  weight: 180,
  description: "Áo cầu lông Lining T72 với thiết kế trắng tinh tế, chất liệu mát, thấm hút mồ hôi tốt, phù hợp thi đấu và luyện tập.",
  imageUrl: "img/ao/ao-cau-long-lining-t72-nam-trang_1745805181.png"
},
{
  id: 34,
  name: "Áo cầu lông Victor A581 Nam - Đen",
  price: 220000,
  brand: "Victor",
  material: "Polyester co giãn",
  length: "M",
  weight: 190,
  description: "Áo cầu lông Victor A581 màu đen mạnh mẽ, thiết kế thể thao, thoáng khí và nhanh khô cho vận động hiệu quả.",
  imageUrl: "img/ao/ao-cau-long-victor-a581-nam-den_1745804424.png"
},
{
  id: 35,
  name: "Áo cầu lông Victor A583 Nam - Xanh",
  price: 130000,
  brand: "Victor",
  material: "Sợi tổng hợp",
  length: "L",
  weight: 185,
  description: "Victor A583 màu xanh nổi bật với khả năng co giãn tốt, thấm hút mồ hôi hiệu quả, lý tưởng cho các buổi tập.",
  imageUrl: "img/ao/ao-cau-long-victor-a583-nam-xanh_1745804792.png"
},
{
  id: 36,
  name: "Áo cầu lông Victor A584 Nam - Xanh",
  price: 110000,
  brand: "Victor",
  material: "Polyester",
  length: "XL",
  weight: 190,
  description: "Thiết kế đơn giản nhưng tinh tế, áo cầu lông Victor A584 đem lại cảm giác thoải mái khi vận động.",
  imageUrl: "img/ao/ao-cau-long-victor-a584-nam-xanh_1745804955.png"
},
{
  id: 37,
  name: "Áo cầu lông Yonex A575 Nam - Xanh",
  price: 150000,
  brand: "Yonex",
  material: "Polyester & Cotton",
  length: "L",
  weight: 180,
  description: "Áo Yonex A575 với gam màu xanh mát, phù hợp cả khi thi đấu và luyện tập, co giãn thoải mái.",
  imageUrl: "img/ao/ao-cau-long-yonex-a575-nam-xanh_1745798778.png"
},
{
  id: 38,
  name: "Áo cầu lông Yonex A589 Nam - Trắng",
  price: 140000,
  brand: "Yonex",
  material: "Polyester cao cấp",
  length: "M",
  weight: 175,
  description: "Yonex A589 với sắc trắng sang trọng, thiết kế thể thao, nhẹ và khô nhanh giúp vận động thoải mái.",
  imageUrl: "img/ao/ao-cau-long-yonex-a589-nam-trang_1745798985.png"
},
{
  id: 39,
  name: "Áo cầu lông Yonex T62 Nam - Trắng",
  price: 129000,
  brand: "Yonex",
  material: "Sợi tổng hợp cao cấp",
  length: "L",
  weight: 180,
  description: "Thiết kế tối giản, áo cầu lông Yonex T62 mang đến cảm giác nhẹ nhàng, phù hợp với mọi đối tượng người chơi.",
  imageUrl: "img/ao/ao-cau-long-yonex-t62-nam-trang_1745799208.png"
},
{
  id: 40,
  name: "Áo cầu lông Yonex T63 Nam - Xanh",
  price: 129000,
  brand: "Yonex",
  material: "Polyester thoáng khí",
  length: "M",
  weight: 175,
  description: "Áo cầu lông Yonex T63 với tông xanh năng động, thiết kế trẻ trung và khả năng kháng khuẩn vượt trội.",
  imageUrl: "img/ao/ao-cau-long-yonex-t63-nam-xanh_1745799056.png"
}
];